from __future__ import annotations

def build_content_css() -> str:
    return r'''
.cui-metric-strip{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:var(--cui-space-3)}
.cui-metric-card{display:flex;flex-direction:column;gap:6px;min-width:0;padding:var(--cui-space-4);border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-md);background:var(--cui-surface);transition:border-color var(--cui-motion-fast) var(--cui-ease-standard),background var(--cui-motion-fast) var(--cui-ease-standard)}
.cui-metric-card.is-clickable{cursor:pointer}.cui-metric-card.is-clickable:hover{border-color:var(--cui-border-default);background:var(--cui-surface-hover)}
.cui-metric-card__top{display:flex;align-items:center;gap:var(--cui-space-2)}.cui-metric-card__label{font-size:var(--cui-type-label-size);font-weight:var(--cui-font-weight-600);color:var(--cui-text-secondary)}.cui-metric-card__value{font-size:var(--cui-font-size-28);line-height:var(--cui-line-height-ratio-1_05);letter-spacing:-.035em;font-weight:var(--cui-font-weight-700);font-variant-numeric:tabular-nums;color:var(--cui-text-primary)}
.cui-metric-card__description{font-size:var(--cui-type-caption-size);color:var(--cui-text-tertiary)}.cui-metric-card__delta{display:inline-flex;align-items:center;gap:4px;width:max-content;font-size:var(--cui-type-caption-size);font-weight:var(--cui-font-weight-600)}.cui-metric-card__delta--success{color:var(--cui-success)}.cui-metric-card__delta--warning{color:var(--cui-warning)}.cui-metric-card__delta--danger{color:var(--cui-danger)}.cui-metric-card__delta--neutral{color:var(--cui-text-secondary)}.cui-metric-card__delta--info{color:var(--cui-info)}
.cui-progress-metric{display:flex;flex-direction:column;gap:8px}.cui-progress-metric__row{display:flex;align-items:baseline;justify-content:space-between;gap:12px}.cui-progress-metric__value{font-variant-numeric:tabular-nums;font-weight:var(--cui-font-weight-650)}
.cui-comparison-metric{display:grid;grid-template-columns:minmax(120px,1fr) repeat(3,minmax(72px,auto));align-items:center;gap:var(--cui-space-3);padding:10px 0;border-bottom:1px solid var(--cui-border-subtle)}.cui-comparison-metric:last-child{border-bottom:0}.cui-comparison-metric__label{font-weight:var(--cui-font-weight-600)}.cui-comparison-metric__value{font-variant-numeric:tabular-nums;text-align:right}.cui-comparison-metric__muted{color:var(--cui-text-tertiary)}
.cui-key-value-list{display:grid;grid-template-columns:minmax(120px,180px) minmax(0,1fr);column-gap:var(--cui-space-4);row-gap:0}.cui-kv-label,.cui-kv-value{padding:8px 0;border-bottom:1px solid var(--cui-border-subtle)}.cui-kv-label{font-size:var(--cui-type-caption-size);color:var(--cui-text-tertiary)}.cui-kv-value{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:var(--cui-type-label-size);color:var(--cui-text-primary);min-width:0}.cui-property-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:var(--cui-border-subtle);border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-md);overflow:hidden}.cui-property-grid .cui-property{background:var(--cui-surface);padding:12px}.cui-property__label{font-size:var(--cui-font-size-10);text-transform:uppercase;letter-spacing:.07em;color:var(--cui-text-tertiary)}.cui-property__value{margin-top:3px;font-size:var(--cui-type-label-size);font-weight:var(--cui-font-weight-600);word-break:break-word}
.cui-entity-header{display:flex;align-items:flex-start;gap:var(--cui-space-3);min-width:0}.cui-entity-header__icon{width:42px;height:42px;border:1px solid var(--cui-border-default);border-radius:var(--cui-radius-surface);display:grid;place-items:center;background:var(--cui-surface-secondary);flex:0 0 auto}.cui-entity-header__copy{flex:1;min-width:0}.cui-entity-header__title{font-size:var(--cui-type-heading-size);font-weight:var(--cui-font-weight-650)}.cui-entity-header__subtitle{font-size:var(--cui-type-caption-size);color:var(--cui-text-secondary);margin-top:2px}.cui-entity-header__meta{display:flex;flex-wrap:wrap;gap:6px 14px;margin-top:8px;color:var(--cui-text-tertiary);font-size:var(--cui-type-caption-size)}
.cui-tree{width:100%;min-width:0;color:var(--cui-text-primary)}.cui-tree .q-tree__node-header{border-radius:var(--cui-radius-inner);min-height:32px}.cui-tree .q-tree__node-header:hover{background:var(--cui-surface-hover)}
.cui-viewer{border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-md);background:var(--cui-surface);overflow:auto;min-width:0}.cui-viewer__toolbar{display:flex;align-items:center;gap:6px;padding:6px 8px;border-bottom:1px solid var(--cui-border-subtle);background:var(--cui-surface-secondary)}.cui-code-viewer{font-variant-ligatures:none}.cui-log-viewer{min-height:180px;max-height:520px}.cui-image-viewer img{max-width:100%;height:auto;display:block;margin:auto}
.cui-search-results{display:flex;flex-direction:column;gap:6px}.cui-search-result{display:flex;align-items:flex-start;gap:12px;padding:12px;border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-md);background:var(--cui-surface);cursor:pointer}.cui-search-result:hover,.cui-search-result:focus-within{background:var(--cui-surface-hover);border-color:var(--cui-border-default)}.cui-search-result__title{font-size:var(--cui-type-label-size);font-weight:var(--cui-font-weight-650)}.cui-search-result__subtitle,.cui-search-result__description{font-size:var(--cui-type-caption-size);color:var(--cui-text-secondary)}.cui-search-result__description{margin-top:4px}
.cui-progress-steps{display:flex;align-items:flex-start;gap:0;overflow-x:auto;padding:2px}.cui-progress-step{position:relative;display:flex;flex:1 0 120px;align-items:center;gap:8px;color:var(--cui-text-tertiary)}.cui-progress-step:not(:last-child)::after{content:'';height:1px;background:var(--cui-border-default);flex:1;min-width:20px}.cui-progress-step__marker{width:26px;height:26px;border-radius:var(--cui-radius-circle);display:grid;place-items:center;border:1px solid var(--cui-border-default);background:var(--cui-surface);font-size:var(--cui-font-size-11);font-weight:var(--cui-font-weight-650);flex:0 0 auto}.cui-progress-step.is-active{color:var(--cui-accent)}.cui-progress-step.is-active .cui-progress-step__marker{border-color:var(--cui-accent);box-shadow:0 0 0 3px var(--cui-accent-soft)}.cui-progress-step.is-complete{color:var(--cui-success)}.cui-progress-step.is-error{color:var(--cui-danger)}.cui-progress-step__label{font-size:var(--cui-type-caption-size);font-weight:var(--cui-font-weight-600);white-space:nowrap}
.cui-compare-panel{display:grid;grid-template-columns:1fr 1fr;gap:var(--cui-space-3)}.cui-compare-side{border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-md);padding:var(--cui-space-4);background:var(--cui-surface)}.cui-difference-table{width:100%;border-collapse:collapse;font-size:var(--cui-type-data-size)}.cui-difference-table th,.cui-difference-table td{padding:8px 10px;border-bottom:1px solid var(--cui-border-subtle);text-align:left}.cui-difference-table .is-changed{background:var(--cui-warning-soft)}
.cui-before-after{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--cui-border-default);border:1px solid var(--cui-border-default);border-radius:var(--cui-radius-md);overflow:hidden}.cui-before-after__side{background:var(--cui-surface);padding:var(--cui-space-4)}.cui-before-after__label{font-size:var(--cui-font-size-10);text-transform:uppercase;letter-spacing:.07em;color:var(--cui-text-tertiary);margin-bottom:8px}
.cui-command-palette{width:min(680px,calc(100vw - 24px));max-height:min(620px,calc(100vh - 48px));display:flex;flex-direction:column;border:1px solid var(--cui-border-default);border-radius:var(--cui-radius-lg);background:var(--cui-surface);box-shadow:var(--cui-shadow-2);overflow:hidden}.cui-command-palette__search{padding:10px;border-bottom:1px solid var(--cui-border-subtle)}.cui-command-palette__results{overflow:auto;padding:6px}.cui-command-palette__item{display:flex;align-items:center;gap:10px;width:100%;padding:8px 10px;border:0;border-radius:var(--cui-radius-inner);background:transparent;text-align:left;color:var(--cui-text-primary)}.cui-command-palette__item:hover,.cui-command-palette__item:focus-visible{background:var(--cui-surface-hover);outline:none}.cui-command-palette__shortcut{margin-left:auto;color:var(--cui-text-tertiary);font-size:var(--cui-font-size-10)}
.cui-background-task{display:flex;align-items:center;gap:10px;padding:8px 10px;border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-md);background:var(--cui-surface)}.cui-background-task__copy{flex:1;min-width:0}.cui-background-task__label{font-size:var(--cui-type-label-size);font-weight:var(--cui-font-weight-600)}.cui-background-task__detail{font-size:var(--cui-type-caption-size);color:var(--cui-text-tertiary)}

.cui-notification-center,.cui-activity-feed{display:flex;flex-direction:column;gap:var(--cui-space-2)}
.cui-notification-item,.cui-activity-item{display:grid;grid-template-columns:auto minmax(0,1fr);gap:var(--cui-space-2);align-items:start;padding:var(--cui-space-3);border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-md);background:var(--cui-surface)}
.cui-notification-item__title,.cui-activity-item__title{font-weight:var(--cui-font-weight-600);color:var(--cui-text-primary)}
.cui-notification-item__detail,.cui-activity-item__detail,.cui-activity-item__meta{color:var(--cui-text-secondary);font-size:var(--cui-type-caption-size)}

/* Content normalizer: third-party/generated content follows Company UI typography. */
.cui-markdown-viewer { padding:var(--cui-space-4); font-size:var(--cui-type-body-size); line-height:var(--cui-line-height-ratio-1_55); }
.cui-markdown-viewer h1,.cui-markdown-viewer h2,.cui-markdown-viewer h3,.cui-markdown-viewer h4 { color:var(--cui-text-primary); letter-spacing:-.018em; margin:1.25em 0 .55em; }
.cui-markdown-viewer h1 { font-size:var(--cui-type-page_title-size); line-height:var(--cui-type-page_title-line); }
.cui-markdown-viewer h2 { font-size:var(--cui-type-heading-size); line-height:var(--cui-type-heading-line); }
.cui-markdown-viewer h3,.cui-markdown-viewer h4 { font-size:var(--cui-type-subheading-size); line-height:var(--cui-type-subheading-line); }
.cui-markdown-viewer p,.cui-markdown-viewer ul,.cui-markdown-viewer ol { color:var(--cui-text-secondary); margin:.55em 0; }
.cui-markdown-viewer a { color:var(--cui-accent); text-decoration:none; text-underline-offset:2px; }
.cui-markdown-viewer a:hover { text-decoration:underline; }
.cui-markdown-viewer blockquote { margin:var(--cui-space-3) 0; padding:var(--cui-space-2) var(--cui-space-3); border-left:3px solid var(--cui-accent); border-radius:0 var(--cui-radius-sm) var(--cui-radius-sm) 0; background:var(--cui-surface-secondary); color:var(--cui-text-secondary); }
.cui-markdown-viewer code,.cui-code-viewer code,.cui-log-viewer { font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace; }
.cui-markdown-viewer :not(pre) > code { padding:2px 5px; border:1px solid var(--cui-border-subtle); border-radius:var(--cui-radius-micro); background:var(--cui-surface-secondary); color:var(--cui-text-primary); font-size:var(--cui-font-size-inline_code); }
.cui-markdown-viewer pre,.cui-code-viewer pre { margin:0; padding:var(--cui-space-4); overflow:auto; background:var(--cui-surface-secondary) !important; color:var(--cui-text-primary) !important; border:0; border-radius:0; font-size:var(--cui-font-size-12); line-height:var(--cui-line-height-ratio-1_55); }
.cui-markdown-viewer table { width:100%; border-collapse:collapse; margin:var(--cui-space-3) 0; font-size:var(--cui-type-data-size); }
.cui-markdown-viewer th { padding:8px 10px; text-align:left; background:var(--cui-surface-secondary); color:var(--cui-text-secondary); border-bottom:1px solid var(--cui-border-default); font-weight:var(--cui-font-weight-650); }
.cui-markdown-viewer td { padding:8px 10px; border-bottom:1px solid var(--cui-border-subtle); color:var(--cui-text-primary); }
.cui-json-viewer .jsoneditor,.cui-json-viewer .jsoneditor-outer { border:0 !important; background:var(--cui-surface) !important; color:var(--cui-text-primary) !important; }
.cui-json-viewer .jsoneditor-menu,.cui-json-viewer .jsoneditor-navigation-bar,.cui-json-viewer .jsoneditor-statusbar { background:var(--cui-surface-secondary) !important; border-color:var(--cui-border-subtle) !important; color:var(--cui-text-secondary) !important; }
.cui-json-viewer .jsoneditor-tree,.cui-json-viewer table.jsoneditor-tree,.cui-json-viewer .jsoneditor-field,.cui-json-viewer .jsoneditor-value { background:var(--cui-surface) !important; color:var(--cui-text-primary) !important; font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace !important; font-size:var(--cui-font-size-12) !important; }
.cui-json-viewer .jsoneditor-string { color:var(--cui-success) !important; }.cui-json-viewer .jsoneditor-number { color:var(--cui-info) !important; }.cui-json-viewer .jsoneditor-boolean { color:var(--cui-warning) !important; }.cui-json-viewer .jsoneditor-null { color:var(--cui-text-tertiary) !important; }
.cui-json-viewer button { filter:grayscale(1); opacity:.72; }.cui-json-viewer button:hover { opacity:1; }
.cui-log-viewer { padding:var(--cui-space-3); background:var(--cui-surface-secondary); color:var(--cui-text-primary); font-size:var(--cui-font-size-12); line-height:var(--cui-line-height-ratio-1_55); scrollbar-color:var(--cui-border-strong) transparent; }

@media(max-width:899px){.cui-metric-strip{grid-template-columns:repeat(2,minmax(0,1fr))}.cui-property-grid,.cui-compare-panel,.cui-before-after{grid-template-columns:1fr}.cui-key-value-list{grid-template-columns:1fr}.cui-kv-label{padding-bottom:0;border-bottom:0}.cui-kv-value{padding-top:2px}.cui-comparison-metric{grid-template-columns:1fr 1fr}.cui-comparison-metric__label{grid-column:1/-1}.cui-progress-steps{padding-bottom:8px}}
@media(max-width:430px){.cui-metric-strip{grid-template-columns:1fr}}
'''

__all__=['build_content_css']
