from __future__ import annotations


def build_mac_lab_css() -> str:
    """Reference-lab-only composition CSS.

    Every custom property used here is part of the framework design constitution;
    this CSS is audited together with framework CSS in v1.6.
    """
    return r'''
:root{--cui-lab-radius:var(--cui-radius-surface);--cui-lab-space:16px;--cui-lab-swatch:var(--cui-surface-secondary)}
.cui-lab-controlbar{position:sticky;top:calc(var(--cui-shell-header-height) + 10px);z-index:var(--cui-layer-sticky);display:flex;align-items:center;gap:var(--cui-cluster-gap);flex-wrap:wrap;padding:10px 12px;margin:0 0 var(--cui-space-5);border:0;border-radius:var(--cui-radius-surface);background:color-mix(in srgb,var(--cui-surface-elevated) 92%,transparent);box-shadow:var(--cui-shadow-1);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
.cui-lab-controlbar__label{font-size:var(--cui-type-caption-size);line-height:var(--cui-type-caption-line);font-weight:var(--cui-font-weight-650);color:var(--cui-text-tertiary);text-transform:uppercase;letter-spacing:.055em}.cui-lab-controlbar__spacer{flex:1 1 auto}
.cui-lab-section{display:flex;flex-direction:column;gap:var(--cui-stack-gap);min-width:0;width:100%}.cui-lab-section+.cui-lab-section{margin-top:var(--cui-section-gap)}
.cui-lab-route-data .cui-lab-controlbar{background:var(--cui-surface-elevated);backdrop-filter:none;-webkit-backdrop-filter:none}
.cui-lab-deferred-wrap{min-width:0;width:100%}.cui-lab-deferred-host:empty{display:none}.cui-lab-deferred{display:flex;align-items:center;justify-content:space-between;gap:var(--cui-space-4);min-height:104px;padding:var(--cui-space-4);border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-surface);background:var(--cui-surface-secondary)}.cui-lab-deferred__copy{display:flex;flex-direction:column;gap:4px;min-width:0}.cui-lab-deferred__title{font-size:var(--cui-type-subheading-size);font-weight:var(--cui-font-weight-650);color:var(--cui-text-primary)}.cui-lab-deferred__description{font-size:var(--cui-type-caption-size);line-height:var(--cui-type-caption-line);color:var(--cui-text-secondary);max-width:720px}
.cui-lab-section__head{display:flex;align-items:flex-start;justify-content:space-between;gap:var(--cui-space-4);min-width:0}.cui-lab-section__title{font-size:var(--cui-type-heading-size);line-height:var(--cui-type-heading-line);font-weight:var(--cui-font-weight-680);letter-spacing:var(--cui-type-heading-tracking);color:var(--cui-text-primary)}.cui-lab-section__description{font-size:var(--cui-type-body-size);line-height:var(--cui-type-body-line);color:var(--cui-text-secondary);max-width:760px;overflow-wrap:anywhere}
.cui-lab-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:var(--cui-stack-gap);min-width:0;width:100%;align-items:stretch}.cui-lab-grid>*{min-width:0}.cui-lab-span-3{grid-column:span 3}.cui-lab-span-4{grid-column:span 4}.cui-lab-span-5{grid-column:span 5}.cui-lab-span-6{grid-column:span 6}.cui-lab-span-7{grid-column:span 7}.cui-lab-span-8{grid-column:span 8}.cui-lab-span-9{grid-column:span 9}.cui-lab-span-12{grid-column:1/-1}
.cui-lab-sample{min-width:0;max-width:100%;overflow:hidden;padding:var(--cui-surface-padding);border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-surface);background:var(--cui-surface)}.cui-lab-sample--soft{background:var(--cui-surface-secondary)}
.cui-lab-sample__title{font-size:var(--cui-type-label-size);line-height:var(--cui-type-label-line);font-weight:var(--cui-font-weight-680);color:var(--cui-text-primary);margin:0 0 12px}.cui-lab-sample__note{font-size:var(--cui-type-caption-size);line-height:var(--cui-type-caption-line);color:var(--cui-text-tertiary);margin-top:10px}
.cui-lab-inline{display:flex;align-items:center;gap:var(--cui-cluster-gap);flex-wrap:wrap;min-width:0;max-width:100%}.cui-lab-stack{display:flex;flex-direction:column;gap:var(--cui-stack-gap);min-width:0;width:100%}
.cui-lab-swatch-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(156px,1fr));gap:var(--cui-stack-gap);width:100%}.cui-lab-swatch{overflow:hidden;border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-surface);background:var(--cui-surface)}.cui-lab-swatch__color{height:72px;background:var(--cui-lab-swatch)}.cui-lab-swatch__copy{padding:10px 12px}.cui-lab-swatch__name{font-size:var(--cui-font-size-12);font-weight:var(--cui-font-weight-680);color:var(--cui-text-primary)}.cui-lab-swatch__token{font:var(--cui-font-size-11)/var(--cui-line-height-ratio-1_45) ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--cui-text-tertiary);overflow-wrap:anywhere}
.cui-lab-type-display{font-size:var(--cui-type-display-size);line-height:var(--cui-type-display-line);font-weight:var(--cui-type-display-weight);letter-spacing:var(--cui-type-display-tracking)}.cui-lab-type-page{font-size:var(--cui-type-page_title-size);line-height:var(--cui-type-page_title-line);font-weight:var(--cui-type-page_title-weight);letter-spacing:var(--cui-type-page_title-tracking)}.cui-lab-type-heading{font-size:var(--cui-type-heading-size);line-height:var(--cui-type-heading-line);font-weight:var(--cui-font-weight-680)}.cui-lab-type-subheading{font-size:var(--cui-type-subheading-size);line-height:var(--cui-type-subheading-line);font-weight:var(--cui-font-weight-650)}.cui-lab-type-body{font-size:var(--cui-type-body-size);line-height:var(--cui-type-body-line)}.cui-lab-type-label{font-size:var(--cui-type-label-size);line-height:var(--cui-type-label-line);font-weight:var(--cui-font-weight-650)}.cui-lab-type-caption{font-size:var(--cui-type-caption-size);line-height:var(--cui-type-caption-line);color:var(--cui-text-tertiary)}
.cui-lab-spacing-row{display:flex;align-items:center;gap:12px;min-width:0}.cui-lab-spacing-block{height:12px;border-radius:var(--cui-radius-inner);background:var(--cui-accent);width:var(--cui-lab-space);max-width:70%}.cui-lab-token-code{font:var(--cui-font-size-11)/var(--cui-line-height-ratio-1_4) ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--cui-text-secondary);overflow-wrap:anywhere}
.cui-lab-radius-row{display:flex;gap:var(--cui-stack-gap);flex-wrap:wrap}.cui-lab-radius{width:86px;height:60px;border:1px solid var(--cui-border-subtle);background:var(--cui-surface-secondary);border-radius:var(--cui-lab-radius)}
.cui-lab-edge-case{max-width:100%;overflow:hidden}.cui-lab-long-string{max-width:100%;overflow-wrap:anywhere;word-break:break-word;font:var(--cui-font-size-12)/var(--cui-line-height-ratio-1_5) ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--cui-text-secondary)}
.cui-lab-cert-row{display:grid;grid-template-columns:minmax(160px,1fr) minmax(100px,auto) minmax(220px,2fr);gap:12px;align-items:center;padding:10px 0;border-bottom:1px solid var(--cui-border-subtle);min-width:0}.cui-lab-cert-row:last-child{border-bottom:0}.cui-lab-cert-key{font-weight:var(--cui-font-weight-650);color:var(--cui-text-primary)}.cui-lab-cert-detail{color:var(--cui-text-secondary);font-size:var(--cui-font-size-12);overflow-wrap:anywhere}
.cui-lab-phone-note{display:none}.cui-lab-hero{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(280px,.75fr);gap:var(--cui-stack-gap);align-items:stretch;width:100%;min-width:0}.cui-lab-hero__copy{padding:32px;border-radius:var(--cui-radius-overlay);border:1px solid var(--cui-border-subtle);background:linear-gradient(145deg,var(--cui-surface),var(--cui-surface-secondary));overflow:hidden}.cui-lab-hero__eyebrow{font-size:var(--cui-font-size-11);font-weight:var(--cui-font-weight-750);text-transform:uppercase;letter-spacing:.09em;color:var(--cui-accent)}.cui-lab-hero__title{margin-top:10px;font-size:var(--cui-font-size-32);line-height:var(--cui-line-height-ratio-1_12);font-weight:var(--cui-font-weight-750);letter-spacing:-.035em;color:var(--cui-text-primary);overflow-wrap:anywhere}.cui-lab-hero__body{max-width:780px;margin-top:12px;font-size:var(--cui-font-size-14);line-height:var(--cui-line-height-ratio-1_65);color:var(--cui-text-secondary)}
.cui-lab-command{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 14px;border-radius:var(--cui-radius-control);background:var(--cui-surface-secondary);font:var(--cui-font-size-12)/var(--cui-line-height-ratio-1_45) ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--cui-text-primary);min-width:0}.cui-lab-command>*{min-width:0;overflow-wrap:anywhere}.cui-lab-kbd{display:inline-flex;align-items:center;min-height:22px;padding:0 7px;border:1px solid var(--cui-border-default);border-bottom-color:var(--cui-border-strong);border-radius:var(--cui-radius-inner);background:var(--cui-surface);box-shadow:0 1px 1px rgb(0 0 0/.06);font:var(--cui-font-size-11) ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--cui-text-secondary)}
.cui-lab-stress-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--cui-stack-gap);width:100%}.cui-lab-stress-strip>*{min-width:0}.cui-lab-viewport-badge{display:inline-flex;align-items:center;gap:6px;font-size:var(--cui-font-size-11);color:var(--cui-text-tertiary)}
.cui-lab-custom-field{min-height:var(--cui-control-height);display:flex;align-items:center;padding:0 12px;color:var(--cui-text-secondary)}
@media(max-width:899px){.cui-lab-hero{grid-template-columns:1fr}.cui-lab-span-3,.cui-lab-span-4,.cui-lab-span-5,.cui-lab-span-6,.cui-lab-span-7,.cui-lab-span-8,.cui-lab-span-9{grid-column:span 6}.cui-lab-stress-strip{grid-template-columns:repeat(2,minmax(0,1fr))}.cui-lab-cert-row{grid-template-columns:minmax(130px,1fr) auto minmax(180px,1.5fr)}}
@media(max-width:599px){.cui-lab-controlbar{position:relative;top:auto;margin:0 0 var(--cui-space-4)}.cui-lab-controlbar__spacer{display:none}.cui-lab-grid{grid-template-columns:minmax(0,1fr)}.cui-lab-span-3,.cui-lab-span-4,.cui-lab-span-5,.cui-lab-span-6,.cui-lab-span-7,.cui-lab-span-8,.cui-lab-span-9,.cui-lab-span-12{grid-column:1/-1}.cui-lab-stress-strip{grid-template-columns:1fr}.cui-lab-phone-note{display:block}.cui-lab-hero__copy{padding:22px}.cui-lab-hero__title{font-size:var(--cui-font-size-26)}.cui-lab-cert-row{grid-template-columns:1fr;gap:4px}.cui-lab-command{align-items:flex-start;flex-direction:column}}
'''

__all__=['build_mac_lab_css']
