from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from company_ui.design.css import build_css
from company_ui.layouts.css import build_layout_css
from company_ui.components.css import build_component_css
from company_ui.interaction_css import build_interaction_css

base_css = '\n'.join((build_css(), build_layout_css(), build_component_css(), build_interaction_css()))
extra_css = r'''
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0}button,input,select,textarea{font:inherit}
body{background:var(--cui-page)}
.review-bar{position:sticky;top:0;z-index:2000;height:54px;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:0 16px;border-bottom:1px solid var(--cui-border-subtle);background:color-mix(in srgb,var(--cui-surface) 92%,transparent);backdrop-filter:blur(16px)}
.review-title{font-size:12px;font-weight:650}.review-note{font-size:10px;color:var(--cui-text-tertiary)}.review-controls{display:flex;gap:7px;align-items:center;flex-wrap:wrap}
.segment{display:inline-flex;padding:2px;border:1px solid var(--cui-border-default);background:var(--cui-surface-secondary);border-radius:var(--cui-radius-sm)}.segment button{border:0;background:transparent;color:var(--cui-text-secondary);border-radius:6px;padding:5px 8px;font-size:10px;cursor:pointer}.segment button.active{background:var(--cui-surface);color:var(--cui-text-primary);box-shadow:var(--cui-shadow-1)}
.stage{padding:18px;display:flex;justify-content:center}.app-frame{width:min(1440px,100%);min-height:850px;border:1px solid var(--cui-border-default);border-radius:var(--cui-radius-lg);overflow:hidden;background:var(--cui-page);box-shadow:var(--cui-shadow-2);transition:width var(--cui-motion-emphasis) var(--cui-ease-standard)}.app-frame[data-viewport=tablet]{width:820px}.app-frame[data-viewport=phone]{width:390px;min-height:820px}
.app{display:grid;grid-template-columns:238px minmax(0,1fr);min-height:850px}.side{background:var(--cui-surface);border-right:1px solid var(--cui-border-subtle);padding:12px}.brand{display:flex;align-items:center;gap:9px;padding:8px 8px 18px}.mark{width:33px;height:33px;border-radius:10px;display:grid;place-items:center;background:var(--cui-accent);color:var(--cui-text-inverse);font-size:11px;font-weight:750}.brand b{font-size:12px}.brand span{display:block;font-size:10px;color:var(--cui-text-tertiary)}.nav-label{padding:12px 9px 5px;font-size:9px;text-transform:uppercase;letter-spacing:.09em;color:var(--cui-text-tertiary)}.nav-item{display:flex;align-items:center;gap:8px;padding:8px 9px;border-radius:8px;color:var(--cui-text-secondary);font-size:11px;margin:2px 0}.nav-item.active{background:var(--cui-accent-soft);color:var(--cui-accent);font-weight:650}.nav-glyph{width:17px;text-align:center;color:currentColor}
.main{min-width:0}.top{height:54px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;background:color-mix(in srgb,var(--cui-surface) 92%,transparent);border-bottom:1px solid var(--cui-border-subtle);backdrop-filter:blur(14px)}.top-left{font-size:11px;color:var(--cui-text-secondary)}.top-actions{display:flex;gap:7px;align-items:center}.content{padding:20px;display:flex;flex-direction:column;gap:16px}.page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px}.page-title{font-size:var(--cui-type-page_title-size);line-height:var(--cui-type-page_title-line);font-weight:var(--cui-type-page_title-weight);letter-spacing:var(--cui-type-page_title-tracking)}.page-sub{font-size:12px;color:var(--cui-text-secondary);max-width:720px;margin-top:3px}.page-actions{display:flex;gap:7px}
.summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.metric{padding:13px}.metric .k{font-size:10px;color:var(--cui-text-tertiary)}.metric .v{font-size:22px;font-weight:680;line-height:28px;font-variant-numeric:tabular-nums}.metric .f{font-size:10px;color:var(--cui-text-secondary);margin-top:4px}
.work-grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(280px,.75fr);gap:12px}.panel-pad{padding:14px}.section-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px}.section-title{font-size:13px;font-weight:650}.section-note{font-size:10px;color:var(--cui-text-tertiary)}
.record-list{display:flex;flex-direction:column}.record{display:grid;grid-template-columns:1.2fr .85fr .65fr auto;align-items:center;gap:10px;padding:10px;border-bottom:1px solid var(--cui-border-subtle);cursor:pointer}.record:last-child{border-bottom:0}.record:hover{background:var(--cui-surface-hover)}.record b{font-size:11px}.record span{font-size:10px;color:var(--cui-text-secondary)}.record .mono{font-variant-numeric:tabular-nums}.mini-badge{display:inline-flex;padding:3px 7px;border-radius:999px;background:var(--cui-warning-soft);color:var(--cui-warning);font-size:9px;font-weight:650}.mini-badge.critical{background:var(--cui-danger-soft);color:var(--cui-danger)}.mini-badge.good{background:var(--cui-success-soft);color:var(--cui-success)}
.timeline{display:flex;flex-direction:column;gap:0}.event{display:grid;grid-template-columns:18px 1fr;gap:9px}.event-line{display:flex;flex-direction:column;align-items:center}.event-dot{width:8px;height:8px;border-radius:50%;background:var(--cui-accent);margin-top:5px}.event-stem{width:1px;flex:1;background:var(--cui-border-default);min-height:32px}.event:last-child .event-stem{display:none}.event-copy{padding-bottom:12px}.event-copy b{font-size:10.5px}.event-copy div{font-size:10px;color:var(--cui-text-secondary);margin-top:1px}
.field-demo{display:flex;flex-direction:column;gap:5px}.field-demo label{font-size:11px;font-weight:550}.field-demo input,.field-demo select,.field-demo textarea{width:100%;border:0;outline:0;background:transparent;color:var(--cui-text-primary)}.field-demo textarea{resize:vertical}.form-demo-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.full{grid-column:1/-1}.helper{font-size:10px;color:var(--cui-text-tertiary)}.error-copy{font-size:10px;color:var(--cui-danger)}
.state-gallery{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.state-gallery .cui-state-view{min-height:180px;padding:18px}.state-gallery .cui-state-view__mark{width:38px;height:38px;font-size:15px}.state-gallery .cui-state-view__title{font-size:13px}
.overlay-demo{position:fixed;inset:0;z-index:2500;display:none;align-items:center;justify-content:center}.overlay-demo.open{display:flex}.overlay-demo .cui-overlay-backdrop{position:absolute}.overlay-demo>.cui-dialog{position:relative;z-index:1}.drawer-demo{position:fixed;inset:0;z-index:2450;display:none}.drawer-demo.open{display:block}.drawer-demo .cui-overlay-backdrop{position:absolute}.drawer-demo .cui-drawer{z-index:1}.drawer-form{display:flex;flex-direction:column;gap:14px}.drawer-actions{display:flex;justify-content:flex-end;gap:8px}
.pop-wrap{position:relative}.demo-menu{position:absolute;right:0;top:38px;z-index:30;display:none}.demo-menu.open{display:block}.toast-live{position:fixed;top:70px;right:18px;z-index:2700;display:none}.toast-live.open{display:flex}
.async-panel{display:flex;flex-direction:column;gap:12px}.loading-card{padding:14px;border:1px solid var(--cui-border-subtle);border-radius:var(--cui-radius-md);background:var(--cui-surface-secondary)}
.review-section{width:min(1440px,calc(100% - 36px));margin:0 auto 18px;background:var(--cui-surface);border:1px solid var(--cui-border-default);border-radius:var(--cui-radius-lg);padding:18px}.review-section h2{font-size:18px;margin:0 0 4px}.review-section>p{font-size:11px;color:var(--cui-text-secondary);margin:0 0 14px}.law-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.law{padding:12px;border:1px solid var(--cui-border-subtle);border-radius:10px;background:var(--cui-surface-secondary)}.law b{font-size:11px}.law p{font-size:10px;color:var(--cui-text-secondary);margin:4px 0 0}
.app-frame[data-viewport=tablet] .app{grid-template-columns:66px minmax(0,1fr)}.app-frame[data-viewport=tablet] .brand-copy,.app-frame[data-viewport=tablet] .nav-item span,.app-frame[data-viewport=tablet] .nav-label{display:none}.app-frame[data-viewport=tablet] .brand{justify-content:center}.app-frame[data-viewport=tablet] .nav-item{justify-content:center}.app-frame[data-viewport=tablet] .summary{grid-template-columns:repeat(2,1fr)}.app-frame[data-viewport=tablet] .work-grid{grid-template-columns:1fr}
.app-frame[data-viewport=phone] .app{display:block;min-height:820px}.app-frame[data-viewport=phone] .side{display:none}.app-frame[data-viewport=phone] .top{padding:0 12px}.app-frame[data-viewport=phone] .top-left{font-size:10px}.app-frame[data-viewport=phone] .content{padding:12px;gap:12px}.app-frame[data-viewport=phone] .page-head{display:block}.app-frame[data-viewport=phone] .page-actions{margin-top:10px}.app-frame[data-viewport=phone] .summary{grid-template-columns:repeat(2,1fr)}.app-frame[data-viewport=phone] .work-grid{grid-template-columns:1fr}.app-frame[data-viewport=phone] .record{grid-template-columns:1fr auto}.app-frame[data-viewport=phone] .record .hide-phone{display:none}.app-frame[data-viewport=phone] .cui-filter-bar__controls>.cui-field{display:none}.app-frame[data-viewport=phone] .cui-filter-bar__controls>.is-search{display:flex}.app-frame[data-viewport=phone] .cui-filter-bar__mobile-trigger{display:inline-flex!important}.app-frame[data-viewport=phone] .form-demo-grid{grid-template-columns:1fr}.app-frame[data-viewport=phone] .full{grid-column:auto}
@media(max-width:760px){.review-note{display:none}.stage{padding:8px}.app-frame{border-radius:10px}.law-grid,.state-gallery{grid-template-columns:1fr 1fr}.review-section{width:calc(100% - 16px);padding:13px}.review-bar{padding:0 8px}.review-title{display:none}}
'''

html = r'''<!doctype html><html lang="en" data-theme="light" data-density="compact"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phase 4 — Interaction System</title><style>__BASE__\n__EXTRA__</style></head><body>
<header class="review-bar"><div><div class="review-title">Company UI · Phase 4 Interaction System</div><div class="review-note">Forms · filters · drawers · dialogs · feedback · async states</div></div><div class="review-controls">
<div class="segment"><button data-vp="desktop" class="active">Desktop</button><button data-vp="tablet">Tablet</button><button data-vp="phone">Phone</button></div>
<div class="segment"><button data-density="comfortable">Comfort</button><button data-density="compact" class="active">Compact</button><button data-density="dense">Dense</button></div>
<div class="segment"><button data-theme="light" class="active">Light</button><button data-theme="dark">Dark</button><button data-theme="system">System</button></div>
</div></header>

<div class="stage"><div class="app-frame" id="appFrame" data-viewport="desktop"><div class="app">
<aside class="side"><div class="brand"><div class="mark">EI</div><div class="brand-copy"><b>Equipment Intelligence</b><span>Manufacturing Analytics</span></div></div><div class="nav-label">Workspace</div><div class="nav-item active"><i class="nav-glyph">⌂</i><span>Overview</span></div><div class="nav-item"><i class="nav-glyph">⌕</i><span>Explore</span></div><div class="nav-item"><i class="nav-glyph">⚑</i><span>Excursions</span></div><div class="nav-item"><i class="nav-glyph">↻</i><span>Monitoring</span></div><div class="nav-label">Manage</div><div class="nav-item"><i class="nav-glyph">⚙</i><span>Settings</span></div></aside>
<main class="main"><div class="top"><div class="top-left">Overview / Equipment Health</div><div class="top-actions"><span class="cui-badge cui-badge--success cui-badge--subtle">● Live</span><button class="cui-icon-button cui-icon-button--ghost cui-control--medium" title="Notifications">○</button><div class="pop-wrap"><button class="cui-icon-button cui-icon-button--ghost cui-control--medium" id="moreBtn" title="More actions">•••</button><div class="cui-menu demo-menu" id="actionMenu"><button class="cui-menu-item">Export view <span class="cui-menu-item__shortcut">⌘E</span></button><button class="cui-menu-item">Copy link</button><div class="cui-menu-separator"></div><button class="cui-menu-item is-danger" onclick="openModal('dangerModal')">Delete saved view</button></div></div></div></div>
<div class="content">
<div class="page-head"><div><div class="page-title">Equipment Health</div><div class="page-sub">Investigate current excursions while preserving context. Phase 4 demonstrates the approved interaction vocabulary before the dedicated DataTable and chart phases.</div></div><div class="page-actions"><button class="cui-button cui-button--secondary cui-control--medium" onclick="showToast('View exported successfully')">Export</button><button class="cui-button cui-button--primary cui-control--medium" onclick="openDrawer('editDrawer')">Create investigation</button></div></div>

<div class="cui-banner cui-banner--warning"><div class="cui-alert__icon">!</div><div><div class="cui-alert__title">Data freshness degraded</div><div class="cui-alert__message">Metrology feed is 8 minutes behind. Existing results remain available while refresh retries.</div></div><div class="cui-alert__actions"><button class="cui-button cui-button--ghost cui-control--small" onclick="simulateRefresh()">Retry</button></div></div>

<section class="cui-filter-bar"><div class="cui-preset-strip"><button class="cui-preset is-active">My tools</button><button class="cui-preset">Critical only</button><button class="cui-preset">Last 24 hours</button><button class="cui-preset">Post-PM</button></div><div class="cui-filter-bar__controls">
<div class="cui-field is-search"><div class="cui-field-label">Search</div><div class="cui-field-control cui-control--medium cui-field-width--full">⌕&nbsp;<input aria-label="Search" placeholder="Tool, lot, chamber, recipe" style="border:0;outline:0;background:transparent;color:inherit;width:100%"></div></div>
<div class="cui-field"><div class="cui-field-label">Area</div><div class="cui-field-control cui-control--medium"><select aria-label="Area" style="border:0;background:transparent;color:inherit;width:100%"><option>ETCH</option></select></div></div>
<div class="cui-field"><div class="cui-field-label">Status</div><div class="cui-field-control cui-control--medium"><select aria-label="Status" style="border:0;background:transparent;color:inherit;width:100%"><option>Critical + Watch</option></select></div></div>
<div class="cui-filter-bar__actions"><button class="cui-button cui-button--secondary cui-control--medium cui-filter-bar__mobile-trigger" onclick="openDrawer('filterDrawer')">Filters <span class="cui-filter-count">3</span></button><button class="cui-button cui-button--secondary cui-control--medium" onclick="openDrawer('filterDrawer')">Advanced</button><button class="cui-button cui-button--ghost cui-control--medium">Clear</button></div></div>
<div class="cui-filter-bar__active"><span class="cui-filter-chip"><strong>Area:</strong> ETCH <button>×</button></span><span class="cui-filter-chip"><strong>Status:</strong> Critical + Watch <button>×</button></span><span class="cui-filter-chip"><strong>Period:</strong> 24h <button>×</button></span></div></section>

<div class="summary"><div class="cui-surface cui-surface--panel metric"><div class="k">Critical tools</div><div class="v">7</div><div class="f">2 new since last refresh</div></div><div class="cui-surface cui-surface--panel metric"><div class="k">Affected lots</div><div class="v">184</div><div class="f">Across 11 products</div></div><div class="cui-surface cui-surface--panel metric"><div class="k">Open investigations</div><div class="v">12</div><div class="f">4 assigned to you</div></div><div class="cui-surface cui-surface--panel metric"><div class="k">Feed status</div><div class="v">92%</div><div class="f">Partial · metrology delayed</div></div></div>

<div class="work-grid"><section class="cui-surface cui-surface--panel panel-pad"><div class="section-head"><div><div class="section-title">Priority equipment</div><div class="section-note">Click a record to open the standardized detail drawer</div></div><button class="cui-button cui-button--ghost cui-control--small">View all</button></div><div class="record-list"><div class="record" onclick="openDrawer('detailDrawer')"><div><b>ETCH-021 · Chamber B</b><br><span>Poly etch · RCP-913</span></div><span class="hide-phone">14 affected lots</span><span class="mono hide-phone">+3.8σ</span><span class="mini-badge critical">Critical</span></div><div class="record" onclick="openDrawer('detailDrawer')"><div><b>ETCH-044 · Chamber A</b><br><span>Oxide etch · RCP-201</span></div><span class="hide-phone">8 affected lots</span><span class="mono hide-phone">+2.7σ</span><span class="mini-badge">Watch</span></div><div class="record"><div><b>CVD-108 · Chamber C</b><br><span>Deposition · RCP-330</span></div><span class="hide-phone">3 affected lots</span><span class="mono hide-phone">stable</span><span class="mini-badge good">Normal</span></div></div></section>
<section class="cui-surface cui-surface--panel panel-pad"><div class="section-head"><div><div class="section-title">Recent activity</div><div class="section-note">Secondary context stays lightweight</div></div></div><div class="timeline"><div class="event"><div class="event-line"><span class="event-dot"></span><span class="event-stem"></span></div><div class="event-copy"><b>Investigation assigned</b><div>ETCH-021 · 6 min ago</div></div></div><div class="event"><div class="event-line"><span class="event-dot"></span><span class="event-stem"></span></div><div class="event-copy"><b>Filter view saved</b><div>Critical post-PM tools · 18 min ago</div></div></div><div class="event"><div class="event-line"><span class="event-dot"></span></div><div class="event-copy"><b>Metrology feed delayed</b><div>Partial data state · 24 min ago</div></div></div></div></section></div>

<section class="cui-surface cui-surface--panel panel-pad async-panel"><div class="section-head"><div><div class="section-title">Async content behavior</div><div class="section-note">Existing content remains visible while a refresh is in flight</div></div><button class="cui-button cui-button--secondary cui-control--small" onclick="simulateRefresh()">Refresh</button></div><div class="loading-card" id="asyncContent"><div style="font-size:11px;font-weight:650">Latest equipment snapshot</div><div style="font-size:10px;color:var(--cui-text-secondary);margin-top:3px">Loaded 08:06 · 4,218 equipment records · partial metrology coverage</div></div><div id="asyncProgress" style="display:none"><div class="cui-progress is-indeterminate"><div class="cui-progress__bar"></div></div><div style="font-size:10px;color:var(--cui-text-secondary);margin-top:6px">Refreshing without blanking the existing content…</div></div></section>
</div></main></div></div></div>

<section class="review-section"><h2>Interaction-state gallery</h2><p>These states are first-class components so applications never invent one-off empty/error/permission messaging.</p><div class="state-gallery">
<div class="cui-state-view"><div class="cui-state-view__mark">—</div><div class="cui-state-view__title">No data yet</div><div class="cui-state-view__message">Connect a source or adjust the analysis period.</div><div class="cui-state-view__actions"><button class="cui-button cui-button--primary cui-control--small">Configure</button></div></div>
<div class="cui-state-view cui-state-view--no-results"><div class="cui-state-view__mark">⌕</div><div class="cui-state-view__title">No matching results</div><div class="cui-state-view__message">The current filters exclude all records.</div><div class="cui-state-view__actions"><button class="cui-button cui-button--secondary cui-control--small">Clear filters</button></div></div>
<div class="cui-state-view cui-state-view--error"><div class="cui-state-view__mark">!</div><div class="cui-state-view__title">Unable to load data</div><div class="cui-state-view__message">The previous snapshot is preserved when possible.</div><div class="cui-state-view__error-id">Error ID: EPHI-7F42A9</div><div class="cui-state-view__actions"><button class="cui-button cui-button--secondary cui-control--small">Retry</button></div></div>
<div class="cui-state-view cui-state-view--permission"><div class="cui-state-view__mark">×</div><div class="cui-state-view__title">Access restricted</div><div class="cui-state-view__message">Your current role does not include this operation.</div></div>
<div class="cui-state-view cui-state-view--not-found"><div class="cui-state-view__mark">?</div><div class="cui-state-view__title">Page not found</div><div class="cui-state-view__message">The link may be outdated or the resource was removed.</div><div class="cui-state-view__actions"><button class="cui-button cui-button--secondary cui-control--small">Go back</button></div></div>
<div class="cui-state-view cui-state-view--offline"><div class="cui-state-view__mark">↯</div><div class="cui-state-view__title">Connection unavailable</div><div class="cui-state-view__message">Your existing workspace remains visible where possible.</div><div class="cui-state-view__actions"><button class="cui-button cui-button--secondary cui-control--small">Retry</button></div></div>
</div></section>

<section class="review-section"><h2>Phase 4 UX laws</h2><p>The framework chooses interaction surfaces by purpose rather than appearance.</p><div class="law-grid"><div class="law"><b>Drawer = contextual work</b><p>Inspect or edit while preserving the underlying analytical context.</p></div><div class="law"><b>Dialog = focused decision</b><p>Use for confirmations and short, blocking tasks—not entire applications.</p></div><div class="law"><b>Popover/menu = lightweight action</b><p>Small contextual choices; always dismissible and keyboard reachable.</p></div><div class="law"><b>Feedback stays contextual</b><p>Skeleton for content loading, spinner for short action, progress when measurable, state view for durable conditions.</p></div></div></section>

<div class="drawer-demo" id="detailDrawer"><div class="cui-overlay-backdrop" onclick="closeDrawer('detailDrawer')"></div><aside class="cui-drawer cui-drawer--right cui-drawer--medium"><header class="cui-drawer__header"><div><div class="cui-drawer__title">ETCH-021 · Chamber B</div><div class="cui-drawer__subtitle">Contextual equipment detail</div></div><div class="cui-drawer__actions"><button class="cui-icon-button cui-icon-button--ghost cui-control--medium" onclick="closeDrawer('detailDrawer')">×</button></div></header><div class="cui-drawer__body"><div class="cui-alert cui-alert--danger"><div class="cui-alert__icon">!</div><div><div class="cui-alert__title">Critical excursion</div><div class="cui-alert__message">CD measurement drift exceeds the configured investigation threshold.</div></div></div><div style="height:14px"></div><div class="form-demo-grid"><div><div class="helper">Area</div><b style="font-size:12px">ETCH</b></div><div><div class="helper">Recipe</div><b style="font-size:12px">RCP-913</b></div><div><div class="helper">Affected lots</div><b style="font-size:12px">14</b></div><div><div class="helper">Magnitude</div><b style="font-size:12px">+3.8σ</b></div></div><div style="height:16px"></div><div class="section-title">Recent signals</div><div class="timeline" style="margin-top:10px"><div class="event"><div class="event-line"><span class="event-dot"></span><span class="event-stem"></span></div><div class="event-copy"><b>Metrology OOS</b><div>08:02 · CD +4.1%</div></div></div><div class="event"><div class="event-line"><span class="event-dot"></span></div><div class="event-copy"><b>SPC warning</b><div>07:48 · within control, upward trend</div></div></div></div></div><footer class="cui-drawer__footer"><div class="drawer-actions"><button class="cui-button cui-button--secondary cui-control--medium" onclick="closeDrawer('detailDrawer');openDrawer('editDrawer')">Edit investigation</button><button class="cui-button cui-button--primary cui-control--medium">Open full analysis</button></div></footer></aside></div>

<div class="drawer-demo" id="filterDrawer"><div class="cui-overlay-backdrop" onclick="closeDrawer('filterDrawer')"></div><aside class="cui-drawer cui-drawer--right cui-drawer--medium"><header class="cui-drawer__header"><div><div class="cui-drawer__title">Advanced filters</div><div class="cui-drawer__subtitle">Complex filters leave the primary page uncluttered</div></div><div class="cui-drawer__actions"><button class="cui-icon-button cui-icon-button--ghost cui-control--medium" onclick="closeDrawer('filterDrawer')">×</button></div></header><div class="cui-drawer__body"><div class="drawer-form"><div class="field-demo"><label>Chambers</label><div class="cui-field-control cui-control--medium"><input value="A, B, C"></div><div class="helper">Multiple values supported</div></div><div class="field-demo"><label>Recipe</label><div class="cui-field-control cui-control--medium"><input placeholder="Search recipes"></div></div><div class="field-demo"><label>Excursion magnitude</label><div class="cui-field-control cui-control--medium"><input value="2.0σ – 6.0σ"></div></div><div class="field-demo"><label>Data quality</label><div class="cui-field-control cui-control--medium"><select><option>Complete + Partial</option></select></div></div></div></div><footer class="cui-drawer__footer"><div class="drawer-actions"><button class="cui-button cui-button--secondary cui-control--medium">Reset</button><button class="cui-button cui-button--primary cui-control--medium" onclick="closeDrawer('filterDrawer');showToast('3 filters applied')">Apply filters</button></div></footer></aside></div>

<div class="drawer-demo" id="editDrawer"><div class="cui-overlay-backdrop" onclick="closeDrawer('editDrawer')"></div><aside class="cui-drawer cui-drawer--right cui-drawer--large"><header class="cui-drawer__header"><div><div class="cui-drawer__title">Create investigation</div><div class="cui-drawer__subtitle">Form drawer preserves the current equipment context</div></div><div class="cui-drawer__actions"><span class="cui-dirty-indicator">Unsaved</span><button class="cui-icon-button cui-icon-button--ghost cui-control--medium" onclick="openModal('dirtyModal')">×</button></div></header><div class="cui-drawer__body"><form class="cui-form" onsubmit="return validateForm(event)"><section class="cui-form-section"><div class="cui-form-section__head"><div><div class="cui-form-section__title">Investigation details</div><div class="cui-form-section__description">Required fields use the same validation anatomy as every other form.</div></div></div><div class="cui-validation-summary" id="validationSummary" style="display:none"><div class="cui-validation-summary__icon">!</div><div><div class="cui-validation-summary__title">Please review the highlighted fields</div><ul><li>Title is required.</li></ul></div></div><div class="form-demo-grid"><div class="field-demo full"><label>Title <span style="color:var(--cui-danger)">*</span></label><div class="cui-field-control cui-control--medium" id="titleControl"><input id="investigationTitle" placeholder="e.g. ETCH-021 CD excursion"></div><div class="error-copy" id="titleError" style="display:none">Required</div></div><div class="field-demo"><label>Owner</label><div class="cui-field-control cui-control--medium"><select><option>Process Engineering</option></select></div></div><div class="field-demo"><label>Priority</label><div class="cui-field-control cui-control--medium"><select><option>High</option></select></div></div><div class="field-demo full"><label>Notes</label><div class="cui-field-control" style="min-height:90px"><textarea rows="4" placeholder="Investigation context"></textarea></div></div></div></section></form></div><footer class="cui-drawer__footer"><div class="cui-form-actions cui-form-actions--end" style="border:0;padding:0"><button class="cui-button cui-button--secondary cui-control--medium" onclick="openModal('dirtyModal')">Cancel</button><button class="cui-button cui-button--primary cui-control--medium" onclick="validateForm(event)">Create investigation</button></div></footer></aside></div>

<div class="overlay-demo" id="dangerModal"><div class="cui-overlay-backdrop" onclick="closeModal('dangerModal')"></div><section class="cui-dialog cui-dialog--small cui-dialog--danger"><div class="cui-dialog__head"><div class="cui-dialog__title">Delete saved view?</div><div class="cui-dialog__description">This removes “Critical post-PM tools” from your saved views. The underlying data is not affected.</div></div><div class="cui-dialog__body"><div class="cui-alert cui-alert--warning"><div class="cui-alert__icon">!</div><div><div class="cui-alert__title">This action cannot be undone</div><div class="cui-alert__message">Use destructive confirmation only where reversal is unavailable.</div></div></div></div><footer class="cui-dialog__footer"><button class="cui-button cui-button--secondary cui-control--medium" onclick="closeModal('dangerModal')">Cancel</button><button class="cui-button cui-button--danger cui-control--medium" onclick="closeModal('dangerModal');showToast('Saved view deleted','danger')">Delete view</button></footer></section></div>
<div class="overlay-demo" id="dirtyModal"><div class="cui-overlay-backdrop" onclick="closeModal('dirtyModal')"></div><section class="cui-dialog cui-dialog--small"><div class="cui-dialog__head"><div class="cui-dialog__title">Discard unsaved changes?</div><div class="cui-dialog__description">Your current investigation draft has not been saved.</div></div><footer class="cui-dialog__footer"><button class="cui-button cui-button--secondary cui-control--medium" onclick="closeModal('dirtyModal')">Keep editing</button><button class="cui-button cui-button--danger cui-control--medium" onclick="closeModal('dirtyModal');closeDrawer('editDrawer')">Discard changes</button></footer></section></div>
<div class="cui-toast toast-live" id="liveToast"><div class="cui-toast__dot"></div><div class="cui-toast__message" id="toastText">Saved</div><button class="cui-toast__action" onclick="hideToast()" style="border:0;background:transparent;cursor:pointer">Dismiss</button></div>

<script>
const root=document.documentElement, frame=document.getElementById('appFrame');
document.querySelectorAll('[data-theme]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-theme]').forEach(x=>x.classList.remove('active'));b.classList.add('active');root.dataset.theme=b.dataset.theme}))
document.querySelectorAll('[data-density]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-density]').forEach(x=>x.classList.remove('active'));b.classList.add('active');root.dataset.density=b.dataset.density}))
document.querySelectorAll('[data-vp]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-vp]').forEach(x=>x.classList.remove('active'));b.classList.add('active');frame.dataset.viewport=b.dataset.vp}))
document.getElementById('moreBtn').addEventListener('click',e=>{e.stopPropagation();document.getElementById('actionMenu').classList.toggle('open')});document.addEventListener('click',()=>document.getElementById('actionMenu').classList.remove('open'));
function openDrawer(id){document.getElementById(id).classList.add('open')}function closeDrawer(id){document.getElementById(id).classList.remove('open')}function openModal(id){document.getElementById(id).classList.add('open')}function closeModal(id){document.getElementById(id).classList.remove('open')}
let toastTimer;function showToast(text,intent='success'){const t=document.getElementById('liveToast');document.getElementById('toastText').textContent=text;t.className='cui-toast toast-live open cui-toast--'+intent;clearTimeout(toastTimer);toastTimer=setTimeout(hideToast,3200)}function hideToast(){document.getElementById('liveToast').classList.remove('open')}
function validateForm(e){if(e)e.preventDefault();const input=document.getElementById('investigationTitle'),bad=!input.value.trim();document.getElementById('validationSummary').style.display=bad?'flex':'none';document.getElementById('titleError').style.display=bad?'block':'none';document.getElementById('titleControl').classList.toggle('cui-field-control--error',bad);if(!bad){closeDrawer('editDrawer');showToast('Investigation created')}return false}
function simulateRefresh(){const p=document.getElementById('asyncProgress');p.style.display='block';setTimeout(()=>{p.style.display='none';showToast('Equipment snapshot refreshed')},1500)}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('.drawer-demo.open,.overlay-demo.open').forEach(x=>x.classList.remove('open'));document.getElementById('actionMenu').classList.remove('open')}})
</script></body></html>'''

out = ROOT / 'showcase' / 'phase_4_interaction_showcase.html'
out.write_text(html.replace('__BASE__', base_css).replace('__EXTRA__', extra_css), encoding='utf-8')
print(out)
