from pathlib import Path
from company_ui.design.css import build_css
from company_ui.layouts.css import build_layout_css
from company_ui.components.css import build_component_css
from company_ui.interaction_css import build_interaction_css
from company_ui.data_table.css import build_data_table_css

css='\n'.join((build_css(),build_layout_css(),build_component_css(),build_interaction_css(),build_data_table_css()))
html=f'''<!doctype html>
<html lang="en" data-theme="light" data-density="compact">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Phase 5 — Enterprise DataTable Approval</title>
<style>
{css}
*{{box-sizing:border-box}} html{{background:var(--cui-page)}} body{{margin:0;background:var(--cui-page);color:var(--cui-text-primary);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;font-size:var(--cui-type-body-size);line-height:var(--cui-type-body-line)}}
.demo-shell{{display:grid;grid-template-columns:236px minmax(0,1fr);min-height:100vh}} .demo-side{{position:sticky;top:0;height:100vh;padding:16px;border-right:1px solid var(--cui-border-subtle);background:var(--cui-surface)}} .demo-main{{min-width:0;padding:24px 30px 60px;max-width:1500px;width:100%;margin:0 auto}}
.brand{{display:flex;align-items:center;gap:10px;margin:4px 0 22px}} .brandmark{{width:32px;height:32px;border-radius:9px;background:var(--cui-accent);display:grid;place-items:center;color:var(--cui-text-inverse);font-weight:700}} .brand strong{{display:block}} .brand small{{color:var(--cui-text-tertiary)}}
.navitem{{padding:8px 10px;border-radius:8px;color:var(--cui-text-secondary);font-size:12px;margin:2px 0}} .navitem.active{{background:var(--cui-accent-soft);color:var(--cui-accent);font-weight:600}}
.demo-top{{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:18px}} .demo-top h1{{font-size:26px;letter-spacing:-.025em;margin:0 0 4px}} .demo-top p{{margin:0;color:var(--cui-text-secondary)}} .switches{{display:flex;gap:6px;flex-wrap:wrap}} .demo-btn{{border:1px solid var(--cui-border-default);background:var(--cui-surface);color:var(--cui-text-primary);border-radius:8px;padding:7px 10px;font:inherit;font-size:11px;cursor:pointer}} .demo-btn.active{{background:var(--cui-accent-soft);border-color:color-mix(in srgb,var(--cui-accent) 35%,var(--cui-border-default));color:var(--cui-accent)}}
.demo-banner{{display:flex;align-items:center;gap:8px;padding:10px 12px;border:1px solid var(--cui-border-subtle);border-radius:10px;background:var(--cui-surface);margin-bottom:16px;color:var(--cui-text-secondary);font-size:12px}} .demo-banner b{{color:var(--cui-text-primary)}}
.metric-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}} .metric{{padding:14px;border:1px solid var(--cui-border-subtle);border-radius:12px;background:var(--cui-surface)}} .metric .k{{font-size:11px;color:var(--cui-text-secondary)}} .metric .v{{font-size:22px;font-weight:650;font-variant-numeric:tabular-nums;margin-top:4px}} .metric .s{{font-size:10px;color:var(--cui-text-tertiary)}}
.demo-section{{margin-top:20px}} .demo-section-head{{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:8px}} .demo-section h2{{font-size:17px;margin:0}} .demo-section p{{font-size:11px;color:var(--cui-text-secondary);margin:2px 0 0}}
.toolbar-control{{height:30px;border:1px solid var(--cui-border-default);border-radius:7px;background:var(--cui-surface);color:var(--cui-text-primary);padding:0 9px;font:inherit;font-size:11px}} input.toolbar-control{{min-width:240px}} select.toolbar-control{{min-width:110px}}
.row-check{{width:14px;height:14px;accent-color:var(--cui-accent)}} .expander{{border:0;background:transparent;color:var(--cui-text-secondary);cursor:pointer;width:24px;height:24px;border-radius:6px}} .expander:hover{{background:var(--cui-surface-hover)}}
.action-icon{{border:0;background:transparent;color:var(--cui-text-secondary);width:28px;height:28px;border-radius:7px;cursor:pointer}} .action-icon:hover{{background:var(--cui-surface-hover);color:var(--cui-text-primary)}}
.detail-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}} .detail-cell span{{display:block;font-size:10px;color:var(--cui-text-tertiary);text-transform:uppercase;letter-spacing:.05em}} .detail-cell b{{font-size:12px}}
.spark svg{{display:block;width:80px;height:22px}} .editable-input{{width:76px;height:25px;border:1px solid var(--cui-border-default);border-radius:6px;background:var(--cui-surface);color:var(--cui-text-primary);text-align:right;padding:0 6px;font:inherit;font-size:11px}}
.server-card{{display:grid;grid-template-columns:1fr 280px;gap:12px}} .query-panel{{border:1px solid var(--cui-border-subtle);border-radius:12px;background:var(--cui-surface);padding:14px}} .query-panel pre{{font-size:10px;color:var(--cui-text-secondary);white-space:pre-wrap;margin:8px 0 0;background:var(--cui-surface-secondary);padding:10px;border-radius:8px}}
.state-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}} .state-box{{border:1px solid var(--cui-border-subtle);border-radius:12px;background:var(--cui-surface);min-height:165px;display:grid;place-items:center;text-align:center;padding:16px;color:var(--cui-text-secondary);font-size:11px}} .state-box strong{{display:block;color:var(--cui-text-primary);font-size:13px;margin-bottom:4px}}
.mobile-note{{display:none}} .toast-demo{{position:fixed;right:18px;bottom:18px;padding:10px 13px;border-radius:10px;background:var(--cui-text-primary);color:var(--cui-surface);font-size:11px;box-shadow:var(--cui-shadow-2);opacity:0;transform:translateY(8px);transition:.16s;pointer-events:none}} .toast-demo.show{{opacity:1;transform:none}}
@media(max-width:900px){{.demo-shell{{grid-template-columns:1fr}}.demo-side{{display:none}}.demo-main{{padding:18px 14px 50px}}.metric-grid{{grid-template-columns:1fr 1fr}}.server-card{{grid-template-columns:1fr}}.state-grid{{grid-template-columns:1fr}}.detail-grid{{grid-template-columns:1fr 1fr}}.mobile-note{{display:block}}}}
</style></head>
<body><div class="demo-shell"><aside class="demo-side"><div class="brand"><div class="brandmark">C</div><div><strong>Company UI</strong><small>Phase 5 · DataTable</small></div></div><div class="navitem">Overview</div><div class="navitem active">Equipment Health</div><div class="navitem">Lots & Wafers</div><div class="navitem">Investigations</div><div class="navitem">Settings</div></aside>
<main class="demo-main"><div class="demo-top"><div><h1>Equipment Health</h1><p>Enterprise table system · production interaction target</p></div><div class="switches"><button class="demo-btn active" data-theme-btn="light">Light</button><button class="demo-btn" data-theme-btn="dark">Dark</button><button class="demo-btn" data-density-btn="comfortable">Comfort</button><button class="demo-btn active" data-density-btn="compact">Compact</button><button class="demo-btn" data-density-btn="dense">Dense</button></div></div>
<div class="demo-banner"><b>Phase 5 gate</b><span>Judge table readability, density, selection, discoverability, status treatment, expanded detail, editing, large-data behavior, and mobile prioritization. Charts are intentionally absent.</span></div>
<div class="metric-grid"><div class="metric"><div class="k">Visible tools</div><div class="v" id="metricVisible">12</div><div class="s">Current filtered population</div></div><div class="metric"><div class="k">Critical</div><div class="v">3</div><div class="s">Requires engineering attention</div></div><div class="metric"><div class="k">Average yield</div><div class="v">97.8%</div><div class="s">Last 24 hours</div></div><div class="metric"><div class="k">Selected</div><div class="v" id="metricSelected">0</div><div class="s">Bulk actions available</div></div></div>

<section class="demo-section"><div class="demo-section-head"><div><h2>Tool health table</h2><p>Search, filter, selection, column prioritization, expandable detail and persisted density.</p></div><span class="cui-badge cui-badge--success cui-badge--subtle">Live data</span></div>
<div class="cui-table-shell"><div class="cui-table-headline"><div><div class="cui-table-title">Etch & CMP equipment</div><div class="cui-table-description">12 tools · refreshed 18 seconds ago</div></div><button class="demo-btn" onclick="toast('Table preferences saved')">Save view</button></div>
<div class="cui-table-toolbar"><input class="toolbar-control cui-table-toolbar__search" id="search" placeholder="Search tool, chamber, recipe…"><select class="toolbar-control" id="statusFilter"><option value="">All status</option><option>Normal</option><option>Watch</option><option>Critical</option></select><div class="cui-table-toolbar__spacer"></div><button class="demo-btn" onclick="toast('Column manager opened')">Columns</button><button class="demo-btn" onclick="cycleDensity()">Density</button><button class="demo-btn" onclick="toast('CSV export prepared')">Export</button><button class="demo-btn" onclick="simulateRefresh()">Refresh</button></div>
<div class="cui-table-selection-bar" id="selectionBar" style="display:none"><b id="selectedLabel">0 selected</b><button class="demo-btn">Compare</button><button class="demo-btn">Assign</button><button class="demo-btn">Export</button><div class="cui-table-toolbar__spacer"></div><button class="demo-btn" onclick="clearSelection()">Clear</button></div>
<div class="cui-table-viewport"><table class="cui-data-table cui-data-table--compact" id="mainTable"><thead><tr><th style="width:34px"><input class="row-check" id="selectAll" type="checkbox"></th><th style="width:32px"></th><th>Tool</th><th>Chamber</th><th>Status</th><th class="is-numeric">Yield</th><th class="is-numeric cui-priority-low">Drift</th><th class="cui-priority-low">Recipe</th><th class="cui-priority-low">Trend</th><th style="width:42px"></th></tr></thead><tbody id="tableBody"></tbody></table></div><div class="cui-table-footer"><span id="rowCount">12 records</span><div class="cui-table-footer__spacer"></div><span>Rows per page&nbsp; 25</span><button class="demo-btn" disabled>‹</button><span>1 / 1</span><button class="demo-btn" disabled>›</button></div></div><div class="mobile-note cui-alert cui-alert--info" style="margin-top:8px">On phone, low-priority columns collapse first while the tool, status, yield and row actions remain available.</div></section>

<section class="demo-section"><div class="demo-section-head"><div><h2>Editable maintenance table</h2><p>Editing is opt-in, visually quiet, and validates at the cell/row boundary.</p></div><span class="cui-badge cui-badge--warning cui-badge--subtle">Edit mode</span></div><div class="cui-table-shell"><div class="cui-table-viewport"><table class="cui-data-table cui-data-table--compact"><thead><tr><th>Parameter</th><th class="is-numeric">Current</th><th class="is-numeric">Target</th><th>Owner</th><th>Status</th></tr></thead><tbody><tr><td>RF Match Offset</td><td class="is-numeric">2.4</td><td class="is-numeric"><input class="editable-input" value="2.0" data-valid-min="0" data-valid-max="5"></td><td>Process Eng.</td><td><span class="cui-table-status cui-table-status--warning">Review</span></td></tr><tr><td>Chamber Pressure</td><td class="is-numeric">38.2</td><td class="is-numeric"><input class="editable-input" value="40.0" data-valid-min="35" data-valid-max="45"></td><td>Equipment</td><td><span class="cui-table-status cui-table-status--success">Valid</span></td></tr><tr><td>ESC Temperature</td><td class="is-numeric">68.1</td><td class="is-numeric"><input class="editable-input" value="70.0" data-valid-min="60" data-valid-max="80"></td><td>Process Eng.</td><td><span class="cui-table-status cui-table-status--success">Valid</span></td></tr></tbody></table></div><div class="cui-table-footer"><span>3 editable parameters</span><div class="cui-table-footer__spacer"></div><button class="demo-btn" onclick="toast('Changes discarded')">Cancel</button><button class="demo-btn active" onclick="validateEdits()">Save changes</button></div></div></section>

<section class="demo-section"><div class="demo-section-head"><div><h2>Server-side large-data contract</h2><p>The UI sends query state; repositories/databases own scalable sort, filter and pagination.</p></div><span class="cui-badge cui-badge--info cui-badge--subtle">2.4M source rows</span></div><div class="server-card"><div class="cui-table-shell"><div class="cui-table-toolbar"><input class="toolbar-control cui-table-toolbar__search" placeholder="Lot ID…"><select class="toolbar-control"><option>All products</option><option>Product A</option><option>Product B</option></select><div class="cui-table-toolbar__spacer"></div><button class="demo-btn" onclick="serverNext()">Next page</button></div><div class="cui-table-viewport"><table class="cui-data-table cui-data-table--dense"><thead><tr><th>Lot</th><th>Product</th><th>Tool</th><th>Operation</th><th class="is-numeric">Wafers</th><th>Status</th></tr></thead><tbody id="serverBody"></tbody></table></div><div class="cui-table-footer"><span>2,418,309 matching rows</span><div class="cui-table-footer__spacer"></div><span id="serverPage">Page 1 · 100 rows/query</span></div></div><div class="query-panel"><b>Repository query state</b><pre id="queryState">{{\n  "page": 1,\n  "page_size": 100,\n  "sorts": [{{"key":"event_time","direction":"desc"}}],\n  "filters": []\n}}</pre><p style="font-size:11px;color:var(--cui-text-secondary)">No millions-row dataset is pushed into the browser. ServerDataTable carries only the current window and query contract.</p></div></div></section>

<section class="demo-section"><div class="demo-section-head"><div><h2>Table lifecycle states</h2><p>Loading, empty and error surfaces preserve the table footprint and interaction expectations.</p></div></div><div class="state-grid"><div class="cui-table-shell"><div class="cui-table-loading"><div class="cui-table-loading__row"></div><div class="cui-table-loading__row"></div><div class="cui-table-loading__row"></div><div class="cui-table-loading__row"></div></div></div><div class="state-box"><div><strong>No matching tools</strong>Clear filters or broaden the search criteria.</div></div><div class="state-box"><div><strong>Unable to load equipment</strong>The last good data remains available when possible.<br><button class="demo-btn" style="margin-top:8px" onclick="toast('Retry requested')">Retry</button></div></div></div></section>

</main></div><div id="toast" class="toast-demo">Saved</div>
<script>
const tools=[
['ETCH-021','A','Critical',94.8,'+2.4σ','RCP-713',[4,6,5,8,11,13,15]],['ETCH-017','B','Watch',97.1,'+1.1σ','RCP-713',[9,8,9,10,8,7,6]],['ETCH-034','A','Normal',99.2,'+0.2σ','RCP-911',[8,9,9,10,10,11,11]],['CMP-004','1','Critical',95.6,'+2.0σ','CMP-202',[11,10,9,7,6,5,4]],['ETCH-009','C','Normal',98.9,'-0.1σ','RCP-404',[5,6,7,7,8,9,8]],['CMP-011','2','Watch',97.4,'+0.9σ','CMP-118',[6,7,6,8,7,9,10]],['ETCH-028','B','Normal',99.0,'+0.1σ','RCP-713',[7,8,8,9,9,10,10]],['ETCH-003','A','Critical',96.0,'+1.8σ','RCP-404',[12,11,10,9,7,6,5]],['CMP-019','1','Normal',98.7,'+0.3σ','CMP-202',[6,7,8,8,9,9,10]],['ETCH-041','D','Normal',99.4,'0.0σ','RCP-911',[8,8,9,9,9,10,10]],['CMP-007','3','Watch',97.8,'+0.8σ','CMP-118',[7,6,8,7,9,8,7]],['ETCH-013','C','Normal',98.6,'-0.2σ','RCP-404',[5,6,6,7,8,8,9]]];
const selected=new Set(), expanded=new Set();
function spark(vals){{let max=Math.max(...vals),min=Math.min(...vals),pts=vals.map((v,i)=>`${{i*12}},${{20-(v-min)/(max-min||1)*17}}`).join(' ');return `<span class="spark"><svg viewBox="0 0 80 22"><polyline points="${{pts}}" fill="none" stroke="var(--cui-accent)" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></span>`}}
function status(s){{let m={{Normal:'success',Watch:'warning',Critical:'danger'}};return `<span class="cui-table-status cui-table-status--${{m[s]}}">${{s}}</span>`}}
function render(){{const q=document.getElementById('search').value.toLowerCase(),sf=document.getElementById('statusFilter').value;let rows=tools.filter(r=>(!q||r.slice(0,6).join(' ').toLowerCase().includes(q))&&(!sf||r[2]===sf));let h='';rows.forEach((r,i)=>{{let key=r[0];h+=`<tr class="${{selected.has(key)?'is-selected':''}}"><td><input class="row-check" type="checkbox" ${{selected.has(key)?'checked':''}} onchange="toggleSelect('${{key}}')"></td><td><button class="expander" onclick="toggleExpand('${{key}}')">${{expanded.has(key)?'⌄':'›'}}</button></td><td><b>${{r[0]}}</b></td><td>${{r[1]}}</td><td>${{status(r[2])}}</td><td class="is-numeric ${{r[3]<96?'cui-table-cell--danger':r[3]<98?'cui-table-cell--warning':''}}">${{r[3].toFixed(1)}}%</td><td class="is-numeric cui-priority-low">${{r[4]}}</td><td class="cui-priority-low">${{r[5]}}</td><td class="cui-priority-low">${{spark(r[6])}}</td><td><button class="action-icon" onclick="toast('Actions for ${{key}}')">•••</button></td></tr>`;if(expanded.has(key))h+=`<tr class="cui-table-expanded"><td colspan="10"><div class="detail-grid"><div class="detail-cell"><span>Last PM</span><b>Aug 22 · 02:14</b></div><div class="detail-cell"><span>Current lot</span><b>L260825-184</b></div><div class="detail-cell"><span>Alarm count</span><b>${{r[2]=='Critical'?7:2}} / 24h</b></div><div class="detail-cell"><span>Recommended action</span><b>${{r[2]=='Critical'?'Inspect chamber':'Continue monitoring'}}</b></div></div></td></tr>`;}});document.getElementById('tableBody').innerHTML=h;document.getElementById('rowCount').textContent=`${{rows.length}} records`;document.getElementById('metricVisible').textContent=rows.length;updateSelection();}}
function toggleSelect(k){{selected.has(k)?selected.delete(k):selected.add(k);render()}} function clearSelection(){{selected.clear();document.getElementById('selectAll').checked=false;render()}} function updateSelection(){{let n=selected.size;document.getElementById('metricSelected').textContent=n;document.getElementById('selectedLabel').textContent=`${{n}} selected`;document.getElementById('selectionBar').style.display=n?'flex':'none'}} function toggleExpand(k){{expanded.has(k)?expanded.delete(k):expanded.add(k);render()}}
document.getElementById('selectAll').onchange=e=>{{selected.clear();if(e.target.checked)tools.forEach(r=>selected.add(r[0]));render()}};document.getElementById('search').oninput=render;document.getElementById('statusFilter').onchange=render;
let densities=['comfortable','compact','dense'],di=1;function setDensity(d){{document.documentElement.dataset.density=d;document.querySelectorAll('.cui-data-table').forEach(t=>{{t.classList.remove(...densities.map(x=>'cui-data-table--'+x));t.classList.add('cui-data-table--'+d)}});document.querySelectorAll('[data-density-btn]').forEach(b=>b.classList.toggle('active',b.dataset.densityBtn===d));localStorage.setItem('phase5-density',d)}} function cycleDensity(){{di=(di+1)%3;setDensity(densities[di])}}
document.querySelectorAll('[data-density-btn]').forEach(b=>b.onclick=()=>{{di=densities.indexOf(b.dataset.densityBtn);setDensity(b.dataset.densityBtn)}});document.querySelectorAll('[data-theme-btn]').forEach(b=>b.onclick=()=>{{document.documentElement.dataset.theme=b.dataset.themeBtn;document.querySelectorAll('[data-theme-btn]').forEach(x=>x.classList.toggle('active',x===b));localStorage.setItem('phase5-theme',b.dataset.themeBtn)}});
function toast(msg){{let t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window._tt);window._tt=setTimeout(()=>t.classList.remove('show'),1600)}} function simulateRefresh(){{toast('Refreshing equipment…');setTimeout(()=>toast('Equipment refreshed'),650)}}
document.querySelectorAll('.editable-input').forEach(x=>x.oninput=()=>{{let v=+x.value,min=+x.dataset.validMin,max=+x.dataset.validMax;x.classList.toggle('is-error',!(v>=min&&v<=max))}});function validateEdits(){{let bad=[...document.querySelectorAll('.editable-input')].some(x=>x.classList.contains('is-error'));toast(bad?'Fix invalid values before saving':'3 parameter changes saved')}}
let sp=1;const lots=[['L260825-184','P-A','ETCH-021','METAL ETCH',25,'Hold'],['L260825-193','P-B','ETCH-034','VIA ETCH',24,'Active'],['L260825-201','P-A','CMP-004','CMP1',25,'Review'],['L260825-217','P-C','ETCH-017','OXIDE ETCH',25,'Active'],['L260825-224','P-B','CMP-011','CMP2',23,'Active']];function renderServer(){{document.getElementById('serverBody').innerHTML=lots.map(r=>`<tr>${{r.slice(0,4).map(x=>`<td>${{x}}</td>`).join('')}}<td class="is-numeric">${{r[4]}}</td><td>${{status(r[5]=='Active'?'Normal':r[5]=='Hold'?'Critical':'Watch')}}</td></tr>`).join('')}}function serverNext(){{sp++;document.getElementById('serverPage').textContent=`Page ${{sp}} · 100 rows/query`;document.getElementById('queryState').textContent=JSON.stringify({{page:sp,page_size:100,sorts:[{{key:'event_time',direction:'desc'}}],filters:[]}},null,2);toast(`Server query page ${{sp}}`)}}
let st=localStorage.getItem('phase5-theme');if(st)document.documentElement.dataset.theme=st;let sd=localStorage.getItem('phase5-density');if(sd){{di=densities.indexOf(sd);setDensity(sd)}}render();renderServer();
</script></body></html>'''
out=Path(__file__).with_name('phase_5_datatable_showcase.html');out.write_text(html,encoding='utf-8');print(out)
