from __future__ import annotations


def build_overlay_css() -> str:
    return r'''
.cui-overlay-backdrop{position:fixed;inset:0;z-index:var(--cui-overlay-backdrop-z);background:var(--cui-overlay-scrim);backdrop-filter:blur(2px);animation:cui-fade-in var(--cui-motion-overlay) var(--cui-ease-enter)}
.cui-drawer{position:fixed;top:0;bottom:0;z-index:var(--cui-modal-z);display:flex;flex-direction:column;background:var(--cui-surface);box-shadow:var(--cui-shadow-2);border-color:var(--cui-border-default);border-style:solid;animation:cui-drawer-in var(--cui-motion-overlay) var(--cui-ease-enter)}
.cui-drawer--right{right:0;border-width:0 0 0 1px}.cui-drawer--left{left:0;border-width:0 1px 0 0}.cui-drawer--small{width:min(360px,94vw)}.cui-drawer--medium{width:min(480px,94vw)}.cui-drawer--large{width:min(680px,96vw)}.cui-drawer--x-large{width:min(880px,98vw)}.cui-drawer--full{width:100vw}.cui-drawer__header{display:flex;align-items:flex-start;gap:var(--cui-space-3);padding:var(--cui-space-4);border-bottom:1px solid var(--cui-border-subtle)}.cui-drawer__title{font-size:var(--cui-type-heading-size);font-weight:var(--cui-font-weight-650)}.cui-drawer__subtitle{font-size:var(--cui-type-caption-size);color:var(--cui-text-secondary);margin-top:2px}.cui-drawer__actions{margin-left:auto;display:flex;gap:var(--cui-space-1)}.cui-drawer__body{flex:1;min-height:0;overflow:auto;padding:var(--cui-space-4)}.cui-drawer__footer{padding:var(--cui-space-3) var(--cui-space-4);border-top:1px solid var(--cui-border-subtle);background:var(--cui-surface)}
@keyframes cui-drawer-in{from{opacity:.65;transform:translateX(16px)}to{opacity:1;transform:none}}.cui-drawer--left{animation-name:cui-drawer-in-left}@keyframes cui-drawer-in-left{from{opacity:.65;transform:translateX(-16px)}to{opacity:1;transform:none}}@keyframes cui-fade-in{from{opacity:0}to{opacity:1}}
.cui-dialog{width:min(480px,calc(100vw - 32px));max-height:min(780px,calc(100vh - 32px));overflow:hidden;display:flex;flex-direction:column;border:1px solid var(--cui-border-default);border-radius:var(--cui-radius-lg);background:var(--cui-surface);box-shadow:var(--cui-shadow-2);animation:cui-dialog-in var(--cui-motion-overlay) var(--cui-ease-enter)}.cui-dialog--medium{width:min(620px,calc(100vw - 32px))}.cui-dialog--large{width:min(820px,calc(100vw - 32px))}.cui-dialog--x-large{width:min(1080px,calc(100vw - 32px))}.cui-dialog--full{width:calc(100vw - 24px);height:calc(100vh - 24px);max-height:none}.cui-dialog__head{display:flex;align-items:flex-start;gap:var(--cui-space-3);padding:var(--cui-space-4) var(--cui-space-4) var(--cui-space-3)}.cui-dialog__copy{flex:1;min-width:0}.cui-dialog__title{font-size:var(--cui-type-heading-size);font-weight:var(--cui-font-weight-650)}.cui-dialog__description{font-size:var(--cui-type-caption-size);color:var(--cui-text-secondary);margin-top:4px}.cui-dialog__body{padding:0 var(--cui-space-4) var(--cui-space-4);overflow:auto}.cui-dialog__footer{display:flex;justify-content:flex-end;align-items:center;gap:var(--cui-space-2);padding:var(--cui-space-3) var(--cui-space-4);border-top:1px solid var(--cui-border-subtle);background:var(--cui-surface-secondary)}.cui-dialog__footer-spacer{flex:1}.cui-dialog--danger .cui-dialog__title{color:var(--cui-danger)}@keyframes cui-dialog-in{from{opacity:0;transform:translateY(8px) scale(.985)}to{opacity:1;transform:none}}
.cui-popover__title{font-size:var(--cui-type-label-size);font-weight:var(--cui-font-weight-650);padding:6px 8px;color:var(--cui-text-secondary)}.cui-menu-heading{font-size:var(--cui-font-size-10);text-transform:uppercase;letter-spacing:.07em;color:var(--cui-text-tertiary);padding:6px 8px}.cui-popover,.cui-menu{min-width:190px;max-width:360px;padding:6px;border:1px solid var(--cui-border-default);border-radius:var(--cui-radius-md);background:color-mix(in srgb,var(--cui-surface) 97%,transparent);box-shadow:var(--cui-shadow-2);backdrop-filter:blur(16px)}.cui-menu-item{display:flex;align-items:center;gap:var(--cui-space-2);width:100%;min-height:32px;padding:6px 8px;border:0;border-radius:var(--cui-radius-inner);background:transparent;color:var(--cui-text-primary);text-align:left;font-size:var(--cui-type-label-size);cursor:pointer}.cui-menu-item:hover,.cui-menu-item:focus-visible{background:var(--cui-surface-hover);outline:none}.cui-menu-item.is-danger{color:var(--cui-danger)}.cui-menu-item:disabled{opacity:.45;cursor:not-allowed}.cui-menu-item__shortcut,.cui-menu-shortcut{margin-left:auto;color:var(--cui-text-tertiary);font-size:var(--cui-font-size-10)}.cui-menu-separator{height:1px;background:var(--cui-border-subtle);margin:5px 4px}
.cui-tooltip{max-width:320px;padding:6px 8px;border-radius:var(--cui-radius-inner);background:var(--cui-text-primary);color:var(--cui-surface);font-size:var(--cui-font-size-11);line-height:var(--cui-line-height-ratio-1_35);box-shadow:var(--cui-shadow-1)}
@media(max-width:599px){.cui-drawer{width:100vw!important}.cui-drawer__header{padding-top:calc(var(--cui-space-4) + env(safe-area-inset-top))}.cui-dialog:not(.cui-dialog--small){width:100vw;height:100vh;max-height:none;border-radius:0;border:0}.cui-dialog__head{padding-top:calc(var(--cui-space-4) + env(safe-area-inset-top))}}
@media(prefers-reduced-motion:reduce){.cui-overlay-backdrop,.cui-drawer,.cui-dialog{animation:none!important}}
'''
