from __future__ import annotations


def build_feedback_css() -> str:
    return r'''
.cui-alert,.cui-banner{--_tone:var(--cui-info);--_soft:var(--cui-info-soft);display:flex;align-items:flex-start;gap:var(--cui-space-3);padding:var(--cui-space-3) var(--cui-space-4);border:1px solid color-mix(in srgb,var(--_tone) 24%,var(--cui-border-default));border-radius:var(--cui-radius-md);background:var(--_soft);color:var(--cui-text-primary)}
.cui-alert--success,.cui-banner--success{--_tone:var(--cui-success);--_soft:var(--cui-success-soft)}.cui-alert--warning,.cui-banner--warning{--_tone:var(--cui-warning);--_soft:var(--cui-warning-soft)}.cui-alert--danger,.cui-banner--danger{--_tone:var(--cui-danger);--_soft:var(--cui-danger-soft)}.cui-alert--neutral,.cui-banner--neutral{--_tone:var(--cui-text-tertiary);--_soft:var(--cui-surface-secondary)}
.cui-alert__copy{flex:1;min-width:0}.cui-alert__icon{width:20px;height:20px;border-radius:var(--cui-radius-circle);display:grid;place-items:center;color:var(--_tone);background:color-mix(in srgb,var(--_tone) 12%,transparent);font-size:var(--cui-font-size-11);font-weight:var(--cui-font-weight-750);flex:0 0 auto}.cui-alert__title{font-size:var(--cui-type-label-size);font-weight:var(--cui-font-weight-650)}.cui-alert__message{font-size:var(--cui-type-caption-size);color:var(--cui-text-secondary);margin-top:2px}.cui-alert__actions{margin-left:auto;display:flex;align-items:center;gap:var(--cui-space-1)}
.cui-banner{border-radius:0;border-left:0;border-right:0;padding-block:var(--cui-space-2)}
.cui-toast-stack{position:fixed;top:16px;right:16px;z-index:var(--cui-toast-z);display:flex;flex-direction:column;gap:8px;width:min(380px,calc(100vw - 32px));pointer-events:none}.cui-toast{--_tone:var(--cui-info);display:flex;align-items:flex-start;gap:10px;padding:11px 12px;border:1px solid var(--cui-border-default);border-radius:var(--cui-radius-md);background:color-mix(in srgb,var(--cui-surface) 96%,transparent);box-shadow:var(--cui-shadow-2);backdrop-filter:blur(16px);pointer-events:auto;animation:cui-toast-in var(--cui-motion-overlay) var(--cui-ease-enter)}
.cui-toast--success{--_tone:var(--cui-success)}.cui-toast--warning{--_tone:var(--cui-warning)}.cui-toast--danger{--_tone:var(--cui-danger)}.cui-toast__dot{width:8px;height:8px;border-radius:var(--cui-radius-circle);background:var(--_tone);margin-top:5px}.cui-toast__message{font-size:var(--cui-type-label-size);color:var(--cui-text-primary);flex:1}.cui-toast__action{font-size:var(--cui-type-caption-size);font-weight:var(--cui-font-weight-650);color:var(--cui-accent)}
@keyframes cui-toast-in{from{opacity:0;transform:translateY(-6px) scale(.985)}to{opacity:1;transform:none}}.cui-toast.is-leaving{opacity:0;transform:translateY(-4px) scale(.985);transition:opacity var(--cui-duration-fast) var(--cui-ease-exit),transform var(--cui-duration-fast) var(--cui-ease-exit)}
.cui-progress{height:5px;border-radius:var(--cui-radius-pill);background:var(--cui-surface-secondary);overflow:hidden}.cui-progress__bar{height:100%;border-radius:inherit;background:var(--cui-accent);transition:width var(--cui-motion-standard) var(--cui-ease-standard)}.cui-progress.is-indeterminate .cui-progress__bar{width:38%;animation:cui-progress-run var(--cui-duration-progress-long) var(--cui-easing-in-out) infinite}@keyframes cui-progress-run{0%{transform:translateX(-120%)}100%{transform:translateX(360%)}}
.cui-spinner{width:18px;height:18px;border:2px solid color-mix(in srgb,var(--cui-text-secondary) 25%,transparent);border-top-color:var(--cui-accent);border-radius:var(--cui-radius-circle);animation:cui-spin var(--cui-duration-spinner-soft) var(--cui-easing-linear) infinite}
.cui-skeleton{display:flex;flex-direction:column;gap:var(--cui-space-2)}.cui-skeleton__row{height:12px;border-radius:var(--cui-radius-inner);background:linear-gradient(90deg,var(--cui-surface-secondary) 25%,var(--cui-surface-hover) 40%,var(--cui-surface-secondary) 60%);background-size:260% 100%;animation:cui-shimmer var(--cui-duration-shimmer) var(--cui-easing-native) infinite}.cui-skeleton__row:nth-child(2){width:82%}.cui-skeleton__row:nth-child(3){width:64%}@keyframes cui-shimmer{0%{background-position:100% 0}100%{background-position:-100% 0}}
.cui-state-view{min-height:220px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:var(--cui-space-6);border:1px dashed var(--cui-border-default);border-radius:var(--cui-radius-lg);background:var(--cui-surface-secondary)}.cui-state-view--compact{min-height:140px;padding:var(--cui-space-4)}.cui-state-view__mark{width:46px;height:46px;border-radius:var(--cui-radius-surface);display:grid;place-items:center;background:var(--cui-surface);border:1px solid var(--cui-border-default);box-shadow:var(--cui-shadow-1);color:var(--cui-text-secondary);font-size:var(--cui-font-size-20);margin-bottom:var(--cui-space-3)}.cui-state-view__title{font-size:var(--cui-type-subheading-size);font-weight:var(--cui-font-weight-650)}.cui-state-view__message{max-width:56ch;margin-top:4px;font-size:var(--cui-type-caption-size);color:var(--cui-text-secondary)}.cui-state-view__error-id{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:var(--cui-font-size-10);color:var(--cui-text-tertiary);margin-top:var(--cui-space-2)}.cui-state-view__actions{display:flex;gap:var(--cui-space-2);margin-top:var(--cui-space-4)}
.cui-async-content{position:relative;min-width:0}.cui-async-refresh-indicator{display:flex;align-items:center;gap:8px;margin-top:8px;padding:6px 8px;border-radius:var(--cui-radius-inner);background:var(--cui-surface-secondary)}.cui-async-stale-indicator{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:8px;padding:8px 10px;border:1px solid color-mix(in srgb,var(--cui-warning) 36%,var(--cui-border-subtle));border-radius:var(--cui-radius-inner);background:var(--cui-warning-soft)}.cui-async-stale-indicator__copy{display:flex;align-items:center;gap:8px;min-width:0;color:var(--cui-text-primary)}
.cui-live-region{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
@media(prefers-reduced-motion:reduce){.cui-toast,.cui-progress__bar,.cui-skeleton__row{animation:none!important}}
'''
